In [2]:
import pandas as pd

In [ ]:
data = pd.read_csv("../gesture_classification_dataset.csv")
data.head()

,Unnamed: 0,hand,confidence,x0,y0,z0,x1,y1,z1,x2,...,z18,x19,y19,z19,x20,y20,z20,video,id,label
0,0,Right,0.993049,0.0,0.0,0.0,0.002357,-0.046531,-0.003313,0.015087,...,-0.018853,0.056544,0.002580,-0.015215,0.045729,0.004943,-0.012389,up1.mp4,0,up
1,1,Right,0.991593,0.0,0.0,0.0,0.003563,-0.045035,-0.003620,0.016583,...,-0.018412,0.055614,0.006124,-0.014664,0.045403,0.008020,-0.011686,up1.mp4,1,up
2,2,Right,0.995422,0.0,0.0,0.0,0.003470,-0.045270,-0.002904,0.015930,...,-0.016904,0.053715,0.007098,-0.013519,0.044111,0.009054,-0.010989,up1.mp4,2,up
3,3,Right,0.992950,0.0,0.0,0.0,0.003813,-0.044966,-0.003099,0.016591,...,-0.017317,0.053062,0.007506,-0.013876,0.043321,0.008789,-0.011282,up1.mp4,3,up
4,4,Right,0.992649,0.0,0.0,0.0,0.003478,-0.042344,-0.003210,0.015902,...,-0.018383,0.050211,0.011911,-0.015015,0.040619,0.013236,-0.012110,up1.mp4,4,up

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 69 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1573 non-null   int64
 1   hand        1573 non-null   str
 2   confidence  1573 non-null   float64
 3   x0          1573 non-null   float64
 4   y0          1573 non-null   float64
 5   z0          1573 non-null   float64
 6   x1          1573 non-null   float64
 7   y1          1573 non-null   float64
 8   z1          1573 non-null   float64
 9   x2          1573 non-null   float64
 10  y2          1573 non-null   float64
 11  z2          1573 non-null   float64
 12  x3          1573 non-null   float64
 13  y3          1573 non-null   float64
 14  z3          1573 non-null   float64
 15  x4          1573 non-null   float64
 16  y4          1573 non-null   float64
 17  z4          1573 non-null   float64
 18  x5          1573 non-null   float64
 19  y5          1573 non-null   float64
 20  z5          1573 non-null   float64
 21  x6          1573 non-null   float64
 22  y6          1573 non-null   float64
 23  z6          1573 non-null   float64
 24  x7          1573 non-null   float64
 25  y7          1573 non-null   float64
 26  z7          1573 non-null   float64
 27  x8          1573 non-null   float64
 28  y8          1573 non-null   float64
 29  z8          1573 non-null   float64
 30  x9          1573 non-null   float64
 31  y9          1573 non-null   float64
 32  z9          1573 non-null   float64
 33  x10         1573 non-null   float64
 34  y10         1573 non-null   float64
 35  z10         1573 non-null   float64
 36  x11         1573 non-null   float64
 37  y11         1573 non-null   float64
 38  z11         1573 non-null   float64
 39  x12         1573 non-null   float64
 40  y12         1573 non-null   float64
 41  z12         1573 non-null   float64
 42  x13         1573 non-null   float64
 43  y13         1573 non-null   float64
 44  z13         1573 non-null   float64
 45  x14         1573 non-null   float64
 46  y14         1573 non-null   float64
 47  z14         1573 non-null   float64
 48  x15         1573 non-null   float64
 49  y15         1573 non-null   float64
 50  z15         1573 non-null   float64
 51  x16         1573 non-null   float64
 52  y16         1573 non-null   float64
 53  z16         1573 non-null   float64
 54  x17         1573 non-null   float64
 55  y17         1573 non-null   float64
 56  z17         1573 non-null   float64
 57  x18         1573 non-null   float64
 58  y18         1573 non-null   float64
 59  z18         1573 non-null   float64
 60  x19         1573 non-null   float64
 61  y19         1573 non-null   float64
 62  z19         1573 non-null   float64
 63  x20         1573 non-null   float64
 64  y20         1573 non-null   float64
 65  z20         1573 non-null   float64
 66  video       1573 non-null   str
 67  id          1573 non-null   int64
 68  label       1573 non-null   str
dtypes: float64(64), int64(2), str(3)
memory usage: 848.1 KB

In [6]:
data.describe()

,Unnamed: 0,confidence,x0,y0,z0,x1,y1,z1,x2,y2,...,x18,y18,z18,x19,y19,z19,x20,y20,z20,id
count,1573.000000,1573.000000,1573.0,1573.0,1573.0,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,...,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000
mean,786.000000,0.958990,0.0,0.0,0.0,0.004563,-0.022234,-0.008275,0.012644,-0.049805,...,0.017212,-0.078919,-0.026273,0.014273,-0.078519,-0.024668,0.013336,-0.079408,-0.023079,786.000000
std,454.230301,0.077874,0.0,0.0,0.0,0.023628,0.045363,0.007841,0.045477,0.088146,...,0.061825,0.083219,0.014259,0.057098,0.088580,0.014607,0.054320,0.094728,0.015434,454.230301
min,0.000000,0.512759,0.0,0.0,0.0,-0.051849,-0.110477,-0.046607,-0.091215,-0.180755,...,-0.123359,-0.236048,-0.118897,-0.113750,-0.271871,-0.112822,-0.115969,-0.306741,-0.109288,0.000000
25%,393.000000,0.966909,0.0,0.0,0.0,-0.015109,-0.046906,-0.012298,-0.029352,-0.096981,...,-0.030738,-0.144657,-0.032513,-0.030772,-0.141777,-0.030931,-0.028608,-0.139113,-0.029944,393.000000
50%,786.000000,0.986393,0.0,0.0,0.0,0.008135,-0.029402,-0.007008,0.024203,-0.070445,...,0.019145,-0.100016,-0.025029,0.014689,-0.087016,-0.023091,0.013431,-0.075638,-0.020770,786.000000
75%,1179.000000,0.993940,0.0,0.0,0.0,0.025415,-0.006294,-0.003002,0.051107,-0.028382,...,0.059030,-0.000028,-0.018368,0.056407,0.000501,-0.015888,0.053020,0.000758,-0.013318,1179.000000
max,1572.000000,0.999778,0.0,0.0,0.0,0.046198,0.163006,0.034877,0.089214,0.332129,...,0.206964,0.148440,0.033881,0.162357,0.178587,0.036199,0.166638,0.196892,0.036966,1572.000000

In [7]:
data.columns

Index(['Unnamed: 0', 'hand', 'confidence', 'x0', 'y0', 'z0', 'x1', 'y1', 'z1',
       'x2', 'y2', 'z2', 'x3', 'y3', 'z3', 'x4', 'y4', 'z4', 'x5', 'y5', 'z5',
       'x6', 'y6', 'z6', 'x7', 'y7', 'z7', 'x8', 'y8', 'z8', 'x9', 'y9', 'z9',
       'x10', 'y10', 'z10', 'x11', 'y11', 'z11', 'x12', 'y12', 'z12', 'x13',
       'y13', 'z13', 'x14', 'y14', 'z14', 'x15', 'y15', 'z15', 'x16', 'y16',
       'z16', 'x17', 'y17', 'z17', 'x18', 'y18', 'z18', 'x19', 'y19', 'z19',
       'x20', 'y20', 'z20', 'video', 'id', 'label'],
      dtype='str')

In [8]:
data.drop(columns= ['Unnamed: 0', 'confidence', 'id', 'hand', 'video'], inplace=True)
data.head()

,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,...,x18,y18,z18,x19,y19,z19,x20,y20,z20,label
0,0.0,0.0,0.0,0.002357,-0.046531,-0.003313,0.015087,-0.091500,-0.008970,0.024023,...,0.064948,-0.002125,-0.018853,0.056544,0.002580,-0.015215,0.045729,0.004943,-0.012389,up
1,0.0,0.0,0.0,0.003563,-0.045035,-0.003620,0.016583,-0.087514,-0.009416,0.025929,...,0.064005,0.001478,-0.018412,0.055614,0.006124,-0.014664,0.045403,0.008020,-0.011686,up
2,0.0,0.0,0.0,0.003470,-0.045270,-0.002904,0.015930,-0.085044,-0.008400,0.025883,...,0.061116,0.003558,-0.016904,0.053715,0.007098,-0.013519,0.044111,0.009054,-0.010989,up
3,0.0,0.0,0.0,0.003813,-0.044966,-0.003099,0.016591,-0.083982,-0.008629,0.026379,...,0.060556,0.004051,-0.017317,0.053062,0.007506,-0.013876,0.043321,0.008789,-0.011282,up
4,0.0,0.0,0.0,0.003478,-0.042344,-0.003210,0.015902,-0.080038,-0.008412,0.025001,...,0.058304,0.007675,-0.018383,0.050211,0.011911,-0.015015,0.040619,0.013236,-0.012110,up

In [21]:
data.columns

Index(['x0', 'y0', 'z0', 'x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3',
       'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7', 'y7', 'z7',
       'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10', 'x11', 'y11',
       'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14', 'y14', 'z14',
       'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17', 'z17', 'x18',
       'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20', 'label'],
      dtype='str')

In [38]:
x = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [39]:
from sklearn.preprocessing import LabelEncoder
import pickle as pk

encoder = LabelEncoder()
y = encoder.fit_transform(y)

with open("label_encoder.pkl", "wb") as f:   
    pk.dump(encoder, f )

In [40]:
from sklearn.model_selection import train_test_split

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)
x_train.shape

(1101, 63)

In [46]:
import torch

x_train_tensor = torch.tensor(x_train.values, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test.values, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [47]:
y_train_tensor

tensor([3, 0, 4,  ..., 3, 2, 2])

In [52]:
class GestureClassifier(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.network = torch.nn.Sequential(
            torch.nn.Linear(63, 64),
            torch.nn.ReLU(),

            torch.nn.Linear(64, 32),
            torch.nn.ReLU(),

            torch.nn.Linear(32, 5)
        )

    def forward(self, x):
        return self.network(x)

In [55]:
model = GestureClassifier()

loss_fn = torch.nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)

epochs = 1000

In [57]:
for t in range(epochs):
    
    optimizer.zero_grad()

    y_pred = model(x_train_tensor)

    loss = loss_fn(y_pred, y_train_tensor)

    if (t+1)%50 == 0:
        print(f"epoch: {t+1}, loss : {loss.item()}")

    loss.backward()

    optimizer.step()

epoch: 50, loss : 1.359055757522583
epoch: 100, loss : 0.897819995880127
epoch: 150, loss : 0.6581979990005493
epoch: 200, loss : 0.49853482842445374
epoch: 250, loss : 0.35556459426879883
epoch: 300, loss : 0.264786034822464
epoch: 350, loss : 0.22306056320667267
epoch: 400, loss : 0.1962263137102127
epoch: 450, loss : 0.1756417453289032
epoch: 500, loss : 0.15979528427124023
epoch: 550, loss : 0.14732123911380768
epoch: 600, loss : 0.13741959631443024
epoch: 650, loss : 0.1297578662633896
epoch: 700, loss : 0.12358963489532471
epoch: 750, loss : 0.11837182193994522
epoch: 800, loss : 0.11391004920005798
epoch: 850, loss : 0.10996705293655396
epoch: 900, loss : 0.10636548697948456
epoch: 950, loss : 0.10299582779407501
epoch: 1000, loss : 0.09979673475027084

In [68]:
model.eval()

with torch.no_grad():
    train_outputs = model(x_train_tensor).argmax(dim=1).cpu().numpy()
    test_outputs =  model(x_test_tensor).argmax(dim=1).cpu().numpy()


train_outputs.shape

(1101,)

In [69]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Train accuracy:", accuracy_score(y_train, train_outputs))
print("Accuracy:", accuracy_score(y_test, test_outputs))

Train accuracy: 0.9518619436875567
Accuracy: 0.9470338983050848

In [70]:
print(confusion_matrix(test_outputs, y_test))

[[ 56   0   2   0   0]
 [  0  63   1   8   0]
 [  0   4 193   0   0]
 [  0   9   1  39   0]
 [  0   0   0   0  96]]

In [72]:
print(classification_report(test_outputs, y_test))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98        58
           1       0.83      0.88      0.85        72
           2       0.98      0.98      0.98       197
           3       0.83      0.80      0.81        49
           4       1.00      1.00      1.00        96

    accuracy                           0.95       472
   macro avg       0.93      0.92      0.93       472
weighted avg       0.95      0.95      0.95       472

In [73]:
encoder.classes_

array(['down', 'left', 'none', 'right', 'up'], dtype=object)

In [78]:
import json

folder = 'ver1/'

torch.save(model.state_dict(), folder+"state_dict.pth")

with open(folder+ "LabelEncoder.pkl" , "wb") as f:
    pk.dump(encoder, f)

config = {
    
    "num_features": 63,
    "num_classes": 5,
    "class_names": list(encoder.classes_)
}

with open(folder + "config.json", "w") as f:
    json.dump(config, f, indent=4)

Inference:

version 1 has good accuracy results but its confusing the left and right hand signs
Next, trying to use the handedness feature into the dataset